apiVersion: v1
kind: Namespace
metadata:
  name: kubelet-stats-exporter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: kubelet-stats-exporter
rules:
- apiGroups:
  - ""
  resources:
  - nodes/metrics
  - nodes/stats
  - nodes/proxy
  - nodes # Required when running as a Deployment, to query API for list of nodes
  verbs:
  - get
  - list # Required when running as Deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubelet-stats-exporter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubelet-stats-exporter
subjects:
- kind: ServiceAccount
  name: kubelet-stats-exporter
  namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata: 
  name: kubelet-stats-exporter
