apiVersion: v1
kind: Service
metadata:
  name: kubelet-stats-exporter
  labels: 
    name: kubelet-stats-exporter # ServiceMonitor reqires a labelon the service
spec:
  selector:
    name: kubelet-stats-exporter
  ports:
  - name: metrics
    port: 9113
    protocol: TCP
    targetPort: metrics
  type: ClusterIP
  
